In [23]:
%matplotlib inline 
import matplotlib.pyplot as plt 
import numpy as np 



In [2]:
np.set_printoptions(suppress=True)

In [3]:
a = np.array([[2,3],[5,7],[11,13]])
a

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [4]:
u, d , v = np.linalg.svd(a)

In [5]:
print('u:')
print(u)
print('d:')
print(d)
print('v:')
print(v)

u:
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
d:
[19.40321383  0.71783924]
v:
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [7]:
d_pse = np.zeros((a.shape[0], a.shape[1])).T
d_pse

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
print('valores a reemplzar en D_pse')
print(d_pse[:d.shape[0], :d.shape[0]])

valores a reemplzar en D_pse
[[0. 0.]
 [0. 0.]]


In [9]:
print('valores que usaremos en D_pse')
print(np.linalg.inv(np.diag(d)))

valores que usaremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [10]:
print('D_pse')
d_pse[:d.shape[0], :d.shape[0]]= np.linalg.inv(np.diag(d))
print(d_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [11]:
#la que calculamos nosotros
a_pse = v.T.dot(d_pse).dot(u.T)
a_pse

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [12]:
#ahora calculandola con nunpy
a_pse_calc = np.linalg.pinv(a)
a_pse_calc

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [14]:
print(a_pse.dot(a))

[[ 1. -0.]
 [ 0.  1.]]


In [17]:
np.set_printoptions(suppress=False)

#nos daba casi la identidad porque suprimiamos los valores cercanos a 0 

In [18]:
print(a_pse.dot(a))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


In [19]:
#no tiene la caracteristica de la inversa comun
print(a.dot(a_pse))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


In [20]:
a_pse_2 = np.linalg.inv(a.T.dot(a)).dot(a.T)
a_pse_2

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [21]:
a_pse

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])