In [31]:

import numpy as np 


In [32]:
a = np.array([[3,2],[4,2]])
print(a)

[[3 2]
 [4 2]]


In [33]:
autovalores , autovectores = np.linalg.eig(a)


In [34]:
print(autovalores)
print(autovectores)

[ 5.37228132 -0.37228132]
[[ 0.64456735 -0.51010647]
 [ 0.76454754  0.86011126]]


In [35]:
np.linalg.eig(a)

(array([ 5.37228132, -0.37228132]), array([[ 0.64456735, -0.51010647],
        [ 0.76454754,  0.86011126]]))

In [36]:
#expresamos la matriz a, de otra manera
a_calculada = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
a_calculada

array([[3., 2.],
       [4., 2.]])

In [37]:
a = np.array([[3,2],[2,3]])
a

array([[3, 2],
       [2, 3]])

In [38]:
#comprobando que A es igual a a.T (a traspuesta), es decir, es simetrica
print(a == a.T)

[[ True  True]
 [ True  True]]


In [39]:
#Calcular autovalores y autovectores 
autovalores , autovectores = np.linalg.eig(a)

In [40]:
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [41]:
a_calculada = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
a_calculada

array([[3., 2.],
       [2., 3.]])