In [1]:
%matplotlib inline 
import matplotlib.pyplot as plt 
import numpy as np 
%run ".\\funciones_auxiliares\\graficar_vectores.ipynb"

In [2]:
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
u,d,v = np.linalg.svd(a)


In [5]:
print(u)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [6]:
print(d)

[7.97638869 0.61418515]


In [9]:
#como D es diagonal, es decir, sus otros valores son 0, nos muestra solo los valores distintos de 0, por ego hay q hacer el diag
print(np.diag(d))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [10]:
print(v)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [14]:
magicMatrix = np.array([[D[0],0,0],[0,D[1],0]])
A_calc = U.dot(magicMatrix).dot(V)

In [15]:
A_calc

array([[1., 2., 3.],
       [3., 4., 5.]])